version: '3.8'
services:
  rcon-io:
    container_name: rcon-io
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    ports:
      - 3000:3000