export const DefaultMaps = [{
  id: 'de_dust2',
  name: 'de_dust2',
  filename: 'de_dust2',
  commands: '',
  rating: 0
}, {
  id: 'de_anubis',
  name: 'de_anubis',
  filename: 'de_anubis',
  commands: '',
  rating: 0
}, {
  id: 'de_vertigo',
  name: 'de_vertigo',
  filename: 'de_vertigo',
  commands: '',
  rating: 0
}, {
  id: 'de_ancient',
  name: 'de_ancient',
  filename: 'de_ancient',
  commands: '',
  rating: 0
}, {
  id: 'de_inferno',
  name: 'de_inferno',
  filename: 'de_inferno',
  commands: '',
  rating: 0
}, {
  id: 'de_nuke',
  name: 'de_nuke',
  filename: 'de_nuke',
  commands: '',
  rating: 0
}, {
  id: 'de_overpass',
  name: 'de_overpass',
  filename: 'de_overpass',
  commands: '',
  rating: 0
}, {
  id: 'de_mirage',
  name: 'de_mirage',
  filename: 'de_mirage',
  commands: '',
  rating: 0
}, {
  id: 'cs_italy',
  name: 'cs_italy',
  filename: 'cs_italy',
  commands: '',
  rating: 0
}, {
  id: 'cs_office',
  name: 'cs_office',
  filename: 'cs_office',
  commands: '',
  rating: 0
}]